import { ReactScan } from "@/components/ReactScan";
import type { Metadata } from "next";
import { Toaster } from "sonner";
import "./globals.css";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <ReactScan />
      <body className={"antialiased"}>
        {children}
        <Toaster richColors className="text-black" duration={6000} />
      </body>
    </html>
  );
}
